//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphaneProjesi.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBKUTUPHANEEntities : DbContext
    {
        public DBKUTUPHANEEntities()
            : base("name=DBKUTUPHANEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TBLCEZALAR> TBLCEZALARs { get; set; }
        public virtual DbSet<TBLHAREKET> TBLHAREKETs { get; set; }
        public virtual DbSet<TBLKASA> TBLKASAs { get; set; }
        public virtual DbSet<TBLKATEGORI> TBLKATEGORIs { get; set; }
        public virtual DbSet<TBLKITAP> TBLKITAPs { get; set; }
        public virtual DbSet<TBLPERSONEL> TBLPERSONELs { get; set; }
        public virtual DbSet<TBLUYELER> TBLUYELERs { get; set; }
        public virtual DbSet<TBLYAZAR> TBLYAZARs { get; set; }
        public virtual DbSet<TBLİLETİSİM> TBLİLETİSİM { get; set; }
    }
}
