//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphaneProjesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCEZALAR
    {
        public int ceza_id { get; set; }
        public Nullable<int> uye_id { get; set; }
        public Nullable<int> hareket_id { get; set; }
        public Nullable<System.DateTime> ceza_baslangic { get; set; }
        public Nullable<System.DateTime> ceza_bitis { get; set; }
        public Nullable<decimal> ceza_para { get; set; }
    
        public virtual TBLHAREKET TBLHAREKET { get; set; }
        public virtual TBLUYELER TBLUYELER { get; set; }
    }
}
