//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphaneProjesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKITAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLKITAP()
        {
            this.TBLHAREKETs = new HashSet<TBLHAREKET>();
        }
    
        public int kitap_id { get; set; }
        public string kitap_ad { get; set; }
        public Nullable<int> yazar_id { get; set; }
        public Nullable<byte> kategori_id { get; set; }
        public string BASIMYILI { get; set; }
        public string kitap_yayınevi { get; set; }
        public string kitap_sayfa { get; set; }
        public Nullable<bool> kitap_durum { get; set; }
        public string kitap_resim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLHAREKET> TBLHAREKETs { get; set; }
        public virtual TBLKATEGORI TBLKATEGORI { get; set; }
        public virtual TBLYAZAR TBLYAZAR { get; set; }
    }
}
