//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphaneProjesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLYAZAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLYAZAR()
        {
            this.TBLKITAPs = new HashSet<TBLKITAP>();
        }
    
        public int yazar_id { get; set; }
        public string yazar_ad { get; set; }
        public string yazar_soyad { get; set; }
        public string yazar_detay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKITAP> TBLKITAPs { get; set; }
    }
}
